name: Node Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        shell: bash
        run: |
          npm install

      - name: Ejecutar pruebas
        shell: bash
        run: |
          npm test --if-present
